### ISSUE TITLE
We need a better name than 'Create'

### ISSUE THREAD

**Issue by kentaasvang** [kentaasvang/python_create#3]
We need a better name for the CLI. There are no real criterias other than:

1.  Should be easy to type
2. Not be very long (< 10 characters)

**Comment by jorgeparavicini** [comment]
I could imagine something along py_gen which could stand short for python generate

**Comment by kentaasvang** [comment]
> I could imagine something along py_gen which could stand short for python generate
that could work!

**Comment by kentaasvang** [comment]
Since we have python and (ana)conda, I think following that theme is a good idea. Perhaps **boa** would be a good fit.
