### ISSUE TITLE
Remove bash-script

### ISSUE THREAD

**Issue by kentaasvang** [kentaasvang/python_create#8]
The whole CLI is currently just one big bash-script. Windows has support to run bash-scripts as of Windows 10, but we want the project to be written in python.

**Comment by Satharus** [comment]
I am tackling this issue right now :D, will update once it is done

**Comment by kentaasvang** [comment]
> I am tackling this issue right now :D, will update once it is done

Excellent! I'll will check out you pull-request shortly!
